import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { useCrudMutation } from '../hooks/useCrudMutation';
import { chatHooks } from '../hooks/useChat';
import { Button } from '@subbiah/reusable/components/ui/button';
import { Lightbulb, Menu, RefreshCw } from 'lucide-react';
import { api } from '../lib/api';
import { extractErrorMessage } from '../lib/format';
import { SlideNav } from '../components/SlideNav';
import { PlanListItem } from '../components/PlanListItem';
import { PlanDetailDrawer } from '../components/PlanDetailDrawer';
import type { ModulePlan } from '../types';

const STATUS_FILTERS = ['all', 'pending', 'in_progress', 'completed', 'dismissed'] as const;

export function PlansPage() {
  const navigate = useNavigate();
  const [navOpen, setNavOpen] = useState(false);
  const [activeFilter, setActiveFilter] = useState<string>('all');
  const [selectedPlan, setSelectedPlan] = useState<ModulePlan | null>(null);

  const {
    data: plans = [],
    isLoading,
    isFetching,
    error: fetchError,
    refetch,
  } = useQuery({
    queryKey: ['plans', activeFilter],
    queryFn: () => {
      const status = activeFilter === 'all' ? undefined : activeFilter;
      return api.listPlans(status);
    },
  });

  const deleteMutation = useCrudMutation((id: string) => api.deletePlan(id), [['plans']], {
    onSuccess: (_data, id) => {
      if (selectedPlan?.id === id) setSelectedPlan(null);
    },
  });

  const updateStatusMutation = useCrudMutation(
    ({ plan, newStatus }: { plan: ModulePlan; newStatus: ModulePlan['status'] }) =>
      api.updatePlan(plan.id, { status: newStatus }),
    [['plans']],
    { onSuccess: (updated) => setSelectedPlan(updated) }
  );

  const createChatMutation = chatHooks.useCreateChat();
  const executeMutation = useCrudMutation(
    async (plan: ModulePlan) => {
      const prompt = `## Plan: ${plan.title}\n\n${plan.description}`;
      const chat = await createChatMutation.mutateAsync({ name: plan.title, prompt, type: 'plan' });
      await api.updatePlan(plan.id, { status: 'in_progress' });
      return chat;
    },
    [['plans']],
    { onSuccess: (chat) => navigate(`/chat/${chat.id}`) }
  );

  const error = extractErrorMessage(
    fetchError,
    deleteMutation.error,
    updateStatusMutation.error,
    executeMutation.error
  );

  return (
    <div className="safe-area-top safe-area-bottom flex h-full flex-col">
      <SlideNav isOpen={navOpen} onClose={() => setNavOpen(false)} />

      <header className="flex items-center justify-between border-b border-border px-4 py-3">
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="icon" onClick={() => setNavOpen(true)}>
            <Menu className="h-5 w-5" />
          </Button>
          <Lightbulb className="h-6 w-6 text-primary" />
          <h1 className="text-xl font-bold text-foreground">Plans</h1>
        </div>
        <Button variant="ghost" size="icon" onClick={() => refetch()} disabled={isFetching}>
          <RefreshCw className={`h-5 w-5 ${isFetching ? 'animate-spin' : ''}`} />
        </Button>
      </header>

      {error && (
        <div className="border-b border-destructive bg-destructive/10 px-4 py-2 text-sm text-destructive">
          {error}
        </div>
      )}

      <div className="flex gap-2 overflow-x-auto border-b border-border px-4 py-2">
        {STATUS_FILTERS.map((filter) => (
          <button
            key={filter}
            onClick={() => setActiveFilter(filter)}
            className={`whitespace-nowrap rounded-full px-3 py-1 text-xs font-medium transition-colors ${
              activeFilter === filter
                ? 'bg-primary text-primary-foreground'
                : 'bg-muted text-muted-foreground'
            }`}
          >
            {filter === 'in_progress'
              ? 'In Progress'
              : filter.charAt(0).toUpperCase() + filter.slice(1)}
          </button>
        ))}
      </div>

      <main className="flex-1 overflow-y-auto">
        {isLoading && plans.length === 0 ? (
          <div className="flex h-full items-center justify-center">
            <span className="text-muted-foreground">Loading plans...</span>
          </div>
        ) : plans.length === 0 ? (
          <div className="flex h-full flex-col items-center justify-center gap-4 px-6 text-center">
            <Lightbulb className="h-16 w-16 text-muted-foreground/50" />
            <div>
              <h2 className="text-lg font-semibold text-foreground">No plans yet</h2>
              <p className="mt-1 text-sm text-muted-foreground">
                Plans will be generated by the scheduler as it explores the web for ideas.
              </p>
            </div>
          </div>
        ) : (
          <div className="divide-y divide-border">
            {plans.map((plan) => (
              <PlanListItem
                key={plan.id}
                plan={plan}
                onSelect={setSelectedPlan}
                onDelete={(id) => deleteMutation.mutate(id)}
                onExecute={(p) => executeMutation.mutate(p)}
                isExecuting={
                  executeMutation.isPending && executeMutation.variables?.id === plan.id
                }
              />
            ))}
          </div>
        )}
      </main>

      <PlanDetailDrawer
        plan={selectedPlan}
        onClose={() => setSelectedPlan(null)}
        onExecute={(p) => executeMutation.mutate(p)}
        onStatusChange={(plan, newStatus) => updateStatusMutation.mutate({ plan, newStatus })}
        isExecuting={
          executeMutation.isPending && executeMutation.variables?.id === selectedPlan?.id
        }
      />
    </div>
  );
}
